// Code generated by protoc-gen-go. DO NOT EDIT.
// source: actorconfigs.proto

package data

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ActorConfig struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	CompleteBy           string   `protobuf:"bytes,3,opt,name=completeBy,proto3" json:"completeBy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActorConfig) Reset()         { *m = ActorConfig{} }
func (m *ActorConfig) String() string { return proto.CompactTextString(m) }
func (*ActorConfig) ProtoMessage()    {}
func (*ActorConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_28f7b4af44ae6bf0, []int{0}
}

func (m *ActorConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActorConfig.Unmarshal(m, b)
}
func (m *ActorConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActorConfig.Marshal(b, m, deterministic)
}
func (m *ActorConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActorConfig.Merge(m, src)
}
func (m *ActorConfig) XXX_Size() int {
	return xxx_messageInfo_ActorConfig.Size(m)
}
func (m *ActorConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ActorConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ActorConfig proto.InternalMessageInfo

func (m *ActorConfig) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ActorConfig) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ActorConfig) GetCompleteBy() string {
	if m != nil {
		return m.CompleteBy
	}
	return ""
}

type ActorSystemConfig struct {
	Name                 string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address              string         `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	ActorConfigs         []*ActorConfig `protobuf:"bytes,3,rep,name=actorConfigs,proto3" json:"actorConfigs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ActorSystemConfig) Reset()         { *m = ActorSystemConfig{} }
func (m *ActorSystemConfig) String() string { return proto.CompactTextString(m) }
func (*ActorSystemConfig) ProtoMessage()    {}
func (*ActorSystemConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_28f7b4af44ae6bf0, []int{1}
}

func (m *ActorSystemConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActorSystemConfig.Unmarshal(m, b)
}
func (m *ActorSystemConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActorSystemConfig.Marshal(b, m, deterministic)
}
func (m *ActorSystemConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActorSystemConfig.Merge(m, src)
}
func (m *ActorSystemConfig) XXX_Size() int {
	return xxx_messageInfo_ActorSystemConfig.Size(m)
}
func (m *ActorSystemConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ActorSystemConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ActorSystemConfig proto.InternalMessageInfo

func (m *ActorSystemConfig) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ActorSystemConfig) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ActorSystemConfig) GetActorConfigs() []*ActorConfig {
	if m != nil {
		return m.ActorConfigs
	}
	return nil
}

type FileActorSystemEventConfig struct {
	ActorSystemName      string     `protobuf:"bytes,1,opt,name=actorSystemName,proto3" json:"actorSystemName,omitempty"`
	FileEvent            *FileEvent `protobuf:"bytes,2,opt,name=fileEvent,proto3" json:"fileEvent,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *FileActorSystemEventConfig) Reset()         { *m = FileActorSystemEventConfig{} }
func (m *FileActorSystemEventConfig) String() string { return proto.CompactTextString(m) }
func (*FileActorSystemEventConfig) ProtoMessage()    {}
func (*FileActorSystemEventConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_28f7b4af44ae6bf0, []int{2}
}

func (m *FileActorSystemEventConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileActorSystemEventConfig.Unmarshal(m, b)
}
func (m *FileActorSystemEventConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileActorSystemEventConfig.Marshal(b, m, deterministic)
}
func (m *FileActorSystemEventConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileActorSystemEventConfig.Merge(m, src)
}
func (m *FileActorSystemEventConfig) XXX_Size() int {
	return xxx_messageInfo_FileActorSystemEventConfig.Size(m)
}
func (m *FileActorSystemEventConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_FileActorSystemEventConfig.DiscardUnknown(m)
}

var xxx_messageInfo_FileActorSystemEventConfig proto.InternalMessageInfo

func (m *FileActorSystemEventConfig) GetActorSystemName() string {
	if m != nil {
		return m.ActorSystemName
	}
	return ""
}

func (m *FileActorSystemEventConfig) GetFileEvent() *FileEvent {
	if m != nil {
		return m.FileEvent
	}
	return nil
}

func init() {
	proto.RegisterType((*ActorConfig)(nil), "ActorConfig")
	proto.RegisterType((*ActorSystemConfig)(nil), "ActorSystemConfig")
	proto.RegisterType((*FileActorSystemEventConfig)(nil), "FileActorSystemEventConfig")
}

func init() {
	proto.RegisterFile("actorconfigs.proto", fileDescriptor_28f7b4af44ae6bf0)
}

var fileDescriptor_28f7b4af44ae6bf0 = []byte{
	// 243 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x50, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0xa5, 0x46, 0x94, 0x4e, 0x02, 0xe2, 0x9e, 0x96, 0x1e, 0xa4, 0xe4, 0x14, 0x11, 0x12, 0xa9,
	0x08, 0x5e, 0xad, 0xd8, 0xa3, 0x87, 0x78, 0xd3, 0xd3, 0x34, 0x99, 0x6c, 0x83, 0xd9, 0x4c, 0xc8,
	0xae, 0x4a, 0xff, 0xbd, 0x74, 0x68, 0x48, 0xf4, 0xe8, 0x6d, 0xdf, 0xc7, 0xce, 0x7b, 0x33, 0xa0,
	0xb0, 0xf0, 0xdc, 0x17, 0xdc, 0x56, 0xb5, 0x71, 0x69, 0xd7, 0xb3, 0xe7, 0x45, 0x44, 0x5f, 0xd4,
	0xfa, 0x23, 0x8a, 0xdf, 0x21, 0x7c, 0x3c, 0x78, 0x9e, 0xc4, 0xa3, 0x14, 0x9c, 0xb6, 0x68, 0x49,
	0xcf, 0x96, 0xb3, 0x64, 0x9e, 0xcb, 0x5b, 0x69, 0x38, 0xc7, 0xb2, 0xec, 0xc9, 0x39, 0x7d, 0x22,
	0xf4, 0x00, 0xd5, 0x15, 0x40, 0xc1, 0xb6, 0x6b, 0xc8, 0xd3, 0x7a, 0xaf, 0x03, 0x11, 0x27, 0x4c,
	0xec, 0xe0, 0x52, 0x86, 0xbf, 0xee, 0x9d, 0x27, 0xfb, 0xaf, 0x88, 0x5b, 0x88, 0x70, 0xec, 0xe7,
	0x74, 0xb0, 0x0c, 0x92, 0x70, 0x15, 0xa5, 0x93, 0xd2, 0xf9, 0x2f, 0x47, 0xdc, 0xc1, 0x62, 0x53,
	0x37, 0x34, 0x09, 0x7e, 0x3e, 0x2c, 0x7c, 0x4c, 0x4f, 0xe0, 0x02, 0x47, 0xe5, 0x65, 0x2c, 0xf2,
	0x97, 0x56, 0x09, 0xcc, 0xab, 0xba, 0x21, 0xf9, 0x2c, 0xad, 0xc2, 0x15, 0xa4, 0x9b, 0x81, 0xc9,
	0x47, 0x71, 0x7d, 0xf3, 0x76, 0x6d, 0x6a, 0xbf, 0xfb, 0xdc, 0xa6, 0x05, 0xdb, 0xcc, 0xb8, 0x1d,
	0xf6, 0x16, 0x1f, 0xee, 0x33, 0xc3, 0x59, 0x89, 0x1e, 0xab, 0x86, 0xbf, 0xb3, 0xee, 0xc3, 0x08,
	0xd8, 0x9e, 0xc9, 0xdd, 0xef, 0x7e, 0x02, 0x00, 0x00, 0xff, 0xff, 0xe0, 0x67, 0xdc, 0xfa, 0x9b,
	0x01, 0x00, 0x00,
}
