apiVersion: v1
kind: Service
metadata:
  name: actor
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 3000
  selector:
    name: actor
---
apiVersion: apps/v1    
kind: Deployment
metadata:
  name: actor-deployment
spec:
  selector:
    matchLabels:
      name: actor
  template:
    metadata:
      labels:
        name: actor
    spec:
      containers:
      - name: actor
        image: gauravsharmanitk/actor
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3000