apiVersion: v1
kind: ConfigMap
metadata:
  name: actor-config
  namespace: default
data:
  ACTOR_HTTP_PORT: "8080"
  ACTOR_GRPC_LISTENER_PORT: "3000"
---
apiVersion: v1
kind: Service
metadata:
  name: actor
spec:
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  selector:
    name: actor
---
apiVersion: v1
kind: Service
metadata:
  name: actor-query
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    name: actor
---
apiVersion: apps/v1    
kind: Deployment
metadata:
  name: actor-deployment
spec:
  selector:
    matchLabels:
      name: actor
  template:
    metadata:
      labels:
        name: actor
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
        'consul.hashicorp.com/connect-service-protocol': 'grpc'
    spec:
      containers:
      - name: actor
        image: gauravsharmanitk/actor
        imagePullPolicy: IfNotPresent
        env:
        - name: ACTOR_HTTP_PORT
          valueFrom:
            configMapKeyRef:
              name: actor-config
              key: ACTOR_HTTP_PORT
        - name: ACTOR_GRPC_LISTENER_PORT
          valueFrom:
            configMapKeyRef:
              name: actor-config
              key: ACTOR_GRPC_LISTENER_PORT
        ports:
          - containerPort: 3000
            name: "tcp"
          