apiVersion: v1
kind: ConfigMap
metadata:
  name: sensor-config
  namespace: default
data:
  ACTOR_SERVICE_HOST_PROP_NAME: "CONNECT_ACTOR_SERVICE_HOST"
  ACTOR_SERVICE_PORT_PROP_NAME: "CONNECT_ACTOR_SERVICE_PORT"
  CONNECT_ACTOR_SERVICE_HOST: "127.0.0.1"
  CONNECT_ACTOR_SERVICE_PORT: "8502"
---
apiVersion: v1
kind: Secret
metadata:
  name: myregistrykey
  namespace: default
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogIloyRjFjbUYyYzJoaGNtMWhibWwwYXpwTmVXUnZZMnRsY21oMVlrQXgiCgkJfQoJfSwKCSJIdHRwSGVhZGVycyI6IHsKCQkiVXNlci1BZ2VudCI6ICJEb2NrZXItQ2xpZW50LzE5LjAzLjEgKHdpbmRvd3MpIgoJfQp9
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Service
metadata:
  name: sensor
spec:
  ports:
  - name: http
    port: 80
    targetPort: 3000
  selector:
    name: sensor
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor-deployment
spec:
  selector:
    matchLabels:
      name: sensor
  template:
    metadata:
      labels:
        name: sensor
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
        'consul.hashicorp.com/connect-service-protocol': 'grpc'
        'consul.hashicorp.com/connect-service-upstreams': 'actor:8502'
    spec:
      containers:
      - name: sensor
        image: gauravsharmanitk/sensor:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: CONNECT_ACTOR_SERVICE_HOST
          valueFrom:
            configMapKeyRef:
              name: sensor-config
              key: CONNECT_ACTOR_SERVICE_HOST
        - name: CONNECT_ACTOR_SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              name: sensor-config
              key: CONNECT_ACTOR_SERVICE_PORT
        - name: ACTOR_SERVICE_HOST_PROP_NAME
          valueFrom:
            configMapKeyRef:
              name: sensor-config
              key: ACTOR_SERVICE_HOST_PROP_NAME
        - name: ACTOR_SERVICE_PORT_PROP_NAME
          valueFrom:
            configMapKeyRef:
              name: sensor-config
              key: ACTOR_SERVICE_PORT_PROP_NAME
        ports:
          - containerPort: 3000
            name: "tcp"
      imagePullSecrets:
      - name: myregistrykey